# Generated by Django 5.2.6 on 2025-09-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinsulator',
            name='insulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insulator'),
        ),
    ]
