# Generated by Django 5.2.6 on 2025-09-29 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_requestinsulator_insulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinsulator',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.request'),
        ),
    ]
